# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 589)
        MainWindow.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setGeometry(QtCore.QRect(0, 40, 1000, 460))
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_left_menu_2 = QtWidgets.QFrame(self.Content)
        self.frame_left_menu_2.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu_2.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu_2.setObjectName("frame_left_menu_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_left_menu_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_top_menus_2 = QtWidgets.QFrame(self.frame_left_menu_2)
        self.frame_top_menus_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus_2.setObjectName("frame_top_menus_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_top_menus_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_page_4 = QtWidgets.QPushButton(self.frame_top_menus_2)
        self.btn_page_4.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.page_4))
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_4.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_4.setObjectName("btn_page_4")
        self.verticalLayout_10.addWidget(self.btn_page_4)
        self.btn_page_5 = QtWidgets.QPushButton(self.frame_top_menus_2)
        self.btn_page_5.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.page_5))
        self.btn_page_5.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_5.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_5.setObjectName("btn_page_5")
        self.verticalLayout_10.addWidget(self.btn_page_5)
        self.btn_page_6 = QtWidgets.QPushButton(self.frame_top_menus_2)
        self.btn_page_6.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.page_6))
        self.btn_page_6.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_6.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_6.setObjectName("btn_page_6")
        self.verticalLayout_10.addWidget(self.btn_page_6)
        self.verticalLayout_9.addWidget(self.frame_top_menus_2, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.frame_left_menu_2)
        self.frame_pages_2 = QtWidgets.QFrame(self.Content)
        self.frame_pages_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages_2.setObjectName("frame_pages_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_pages_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_pages_2)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFF;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #FFF;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFF;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_14.addWidget(self.label)
        self.stackedWidget_2.addWidget(self.page_6)
        self.verticalLayout_11.addWidget(self.stackedWidget_2)
        self.horizontalLayout_3.addWidget(self.frame_pages_2)
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setGeometry(QtCore.QRect(0, 0, 1000, 40))
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_toggle_2 = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle_2.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle_2.setObjectName("frame_toggle_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_toggle_2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Btn_Toggle_2 = QtWidgets.QPushButton(self.frame_toggle_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle_2.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle_2.setSizePolicy(sizePolicy)
        self.Btn_Toggle_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.Btn_Toggle_2.setObjectName("Btn_Toggle_2")
        self.verticalLayout_15.addWidget(self.Btn_Toggle_2)
        self.horizontalLayout_4.addWidget(self.frame_toggle_2)
        self.frame_top_2 = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_2.setObjectName("frame_top_2")
        self.horizontalLayout_4.addWidget(self.frame_top_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_page_4.setText(_translate("MainWindow", "Page 1"))
        self.btn_page_5.setText(_translate("MainWindow", "Page 2"))
        self.btn_page_6.setText(_translate("MainWindow", "Page 3"))
        self.label_4.setText(_translate("MainWindow", "PAGE 1"))
        self.label_5.setText(_translate("MainWindow", "PAGE 2"))
        self.label.setText(_translate("MainWindow", "PAGE 3"))
        self.Btn_Toggle_2.setText(_translate("MainWindow", "TOGGLE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
