# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1169, 589)
        MainWindow.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.panelContent = QtWidgets.QFrame(self.centralwidget)
        self.panelContent.setGeometry(QtCore.QRect(260, 100, 911, 431))
        self.panelContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panelContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panelContent.setObjectName("panelContent")
        self.stackedWidget = QtWidgets.QStackedWidget(self.panelContent)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 911, 431))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_crud_cars = QtWidgets.QWidget()
        self.page_crud_cars.setObjectName("page_crud_cars")
        self.label = QtWidgets.QLabel(self.page_crud_cars)
        self.label.setGeometry(QtCore.QRect(270, 160, 161, 71))
        self.label.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_crud_cars)
        self.page_crud_users = QtWidgets.QWidget()
        self.page_crud_users.setObjectName("page_crud_users")
        self.label_2 = QtWidgets.QLabel(self.page_crud_users)
        self.label_2.setGeometry(QtCore.QRect(254, 150, 141, 121))
        self.label_2.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_crud_users)
        self.page_crud_clients = QtWidgets.QWidget()
        self.page_crud_clients.setObjectName("page_crud_clients")
        self.label_3 = QtWidgets.QLabel(self.page_crud_clients)
        self.label_3.setGeometry(QtCore.QRect(294, 170, 141, 81))
        self.label_3.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_crud_clients)
        self.panelTop = QtWidgets.QFrame(self.centralwidget)
        self.panelTop.setGeometry(QtCore.QRect(250, 0, 921, 91))
        self.panelTop.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.panelTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panelTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panelTop.setObjectName("panelTop")
        self.leftPanel = QtWidgets.QFrame(self.centralwidget)
        self.leftPanel.setGeometry(QtCore.QRect(0, 0, 251, 591))
        self.leftPanel.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.leftPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftPanel.setObjectName("leftPanel")
        self.btnCrud_cars = QtWidgets.QPushButton(self.leftPanel)
        self.btnCrud_cars.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_crud_cars))
        self.btnCrud_cars.setGeometry(QtCore.QRect(10, 20, 221, 71))
        self.btnCrud_cars.setObjectName("btnCrud_cars")
        self.btnCrud_users = QtWidgets.QPushButton(self.leftPanel)
        self.btnCrud_users.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_crud_users))
        self.btnCrud_users.setGeometry(QtCore.QRect(10, 120, 221, 71))
        self.btnCrud_users.setObjectName("btnCrud_users")
        self.btnCrud_clients = QtWidgets.QPushButton(self.leftPanel)
        self.btnCrud_clients.clicked.connect(lambda : self.stackedWidget.setCurrentWidget(self.page_crud_clients))
        self.btnCrud_clients.setGeometry(QtCore.QRect(10, 230, 221, 71))
        self.btnCrud_clients.setObjectName("btnCrud_clients")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1169, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CRUD CARS"))
        self.label_2.setText(_translate("MainWindow", "crud users"))
        self.label_3.setText(_translate("MainWindow", "CRUD CLIENTS"))
        self.btnCrud_cars.setText(_translate("MainWindow", "CRUD CARS"))
        self.btnCrud_users.setText(_translate("MainWindow", "CRUD USERS"))
        self.btnCrud_clients.setText(_translate("MainWindow", "CRUD CLIENTS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
